version: '2'
services:
  metadataproxy:
    image: metadataproxy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${HOME}/.aws/credentials:/root/.aws/credentials
    ports:
    - 80:8000
    environment:
      DEBUG: "True"
      MOCK_API: "True"
      AWS_DEFAULT_REGION: "us-east-1"
      IAM_ROLE: "${IAM_ROLE}"
